### ISSUE TITLE
Remember to undo the .path addition in 3.4 and 3.5

### ISSUE THREAD

**Issue by gvanrossum** [brettcannon/path-pep#5]
See http://bugs.python.org/issue22570

These haven't been release yet but Larry is planning releases early June.

Worth mentioning as a task in the PEP? (You already have a mention that it's not needed now.)

**Comment by brettcannon** [comment]
The PEP now has a TODO list based on its current contents (I have not even started reading my email on this topic yet for today so it may change shortly :).
